import os
import json
import xml.etree.ElementTree as ET


def parse_fcs_xml(xml_path, output_json):
    """
    Parses an XML file generated by Kenshi's Forgotten Construction Set (Export Mode).
    Extracts all 'Town' objects and their XYZ coordinates into a JSON dictionary.
    """
    if not os.path.exists(xml_path):
        print(f"Error: Could not find XML file at {xml_path}")
        print("Please open the Forgotten Construction Set (FCS) in the Kenshi game directory.")
        print("Click 'Export' -> 'Export XML' and save the map data to an XML file first.")
        return

    print(f"Parsing Kenshi FCS XML data from: {xml_path}")

    try:
        tree = ET.parse(xml_path)
    except Exception as e:
        print(f"Failed to parse XML: {e}")
        return

    root = tree.getroot()
    city_map = {}

    for item in root.findall(".//Item"):
        item_type = item.get("Type")
        item_name = item.get("Name")

        if item_type in ["Town", "Nest", "Resource"]:
            x, y, z = None, None, None

            for val in item.findall("val"):
                val_name = val.get("name")
                if val_name == "x" or val_name == "px":
                    x = float(val.get("value", 0))
                elif val_name == "y" or val_name == "py":
                    y = float(val.get("value", 0))
                elif val_name == "z" or val_name == "pz":
                    z = float(val.get("value", 0))
                elif val_name == "pos":
                    pos_str = val.get("value", "0 0 0").split()
                    if len(pos_str) == 3:
                        x, y, z = float(pos_str[0]), float(pos_str[1]), float(pos_str[2])

            if item_name and x is not None and y is not None and z is not None:
                city_map[item_name] = {"x": x, "y": y, "z": z}

    with open(output_json, 'w', encoding='utf-8') as f:
        json.dump(city_map, f, indent=4)

    print(f"Success! Extracted {len(city_map)} city/location coordinates.")
    print(f"Saved to: {output_json}")


if __name__ == "__main__":
    xml_file = r'G:\SteamLibrary\steamapps\common\Kenshi\data\export.xml'
    output_file = r'g:\Dev\Kenshi-dev\Kenshi-AI\server\config\kenshi_city_map.json'

    if not os.path.exists(xml_file):
        for root_dir, dirs, files in os.walk(r'G:\SteamLibrary\steamapps\common\Kenshi'):
            for f in files:
                if f.endswith('.xml') and ('export' in f.lower() or 'map' in f.lower()):
                    xml_file = os.path.join(root_dir, f)
                    break
            if os.path.exists(xml_file) and 'editor' not in xml_file.lower():
                break

    parse_fcs_xml(xml_file, output_file)
